[package]
name = "aw9523"
version = "0.1.0"
edition = "2021"
authors = ["Trevor Flahardy"]
license = "MIT"


[dependencies]
embedded-hal = "1.0.0"

[dev-dependencies]
embedded-hal-mock = { version = "0.11", features = ["eh1"] }
